-- ==========================================================
-- CONFIGURAÇÃO
-- ==========================================================

set client_min_messages = WARNING;

-- ==========================================================
-- LIMPEZA (DROP CONSTRAINTS)
-- ==========================================================

alter table if exists recursos
drop constraint if exists fk_recurso_sobrevivente;

alter table if exists sobrevivente_comunidade
drop constraint if exists FK6eo93n5rrilxijyt3emkdo1yl;

alter table if exists sobrevivente_comunidade
drop constraint if exists FKf7bbc999axrn536x6b8bp0101;

alter table if exists sobreviventes_recursos
drop constraint if exists FKanvyykdar9nto6oqobib5ty54;

alter table if exists sobreviventes_recursos
drop constraint if exists FK2xvih9jpjtg2j0txa14dcsnah;

-- ==========================================================
-- LIMPEZA (DROP TABLES)
-- ==========================================================

drop table if exists comunidades cascade;
drop table if exists recursos cascade;
drop table if exists sobrevivente_comunidade cascade;
drop table if exists sobreviventes cascade;
drop table if exists sobreviventes_recursos cascade;
drop table if exists survivor_activity_event cascade;

-- ==========================================================
-- LIMPEZA (DROP SEQUENCE)
-- ==========================================================

drop sequence if exists survivor_activity_event_seq;

-- ==========================================================
-- SEQUENCE
-- ==========================================================

create sequence survivor_activity_event_seq
    start with 1
    increment by 50;

-- ==========================================================
-- TABELAS
-- ==========================================================

create table comunidades (
                             id bigint generated by default as identity,
                             nome varchar(50) not null,
                             zona_segura boolean not null,
                             primary key (id)
);

create table sobreviventes (
                               id bigint generated by default as identity,
                               nome varchar(100) not null,
                               localizacao varchar(80) not null,
                               infectado boolean not null,
                               primary key (id),
                               constraint uk_sobrevivente_nome unique (nome)
);

create table recursos (
                          id bigint generated by default as identity,
                          nome varchar(50) not null,
                          quantidade integer not null,
                          sobrevivente_id bigint not null,
                          primary key (id)
);

create table sobrevivente_comunidade (
                                         comunidade_id bigint not null,
                                         sobrevivente_id bigint not null,
                                         primary key (comunidade_id, sobrevivente_id)
);

create table sobreviventes_recursos (
                                        recursos_id bigint not null unique,
                                        sobrevivente_id bigint not null
);

create table survivor_activity_event (
                                         id bigint not null,
                                         survivor_id bigint not null,
                                         occurred_at timestamptz not null,
                                         score_value integer not null,
                                         event_type varchar(40) not null
                                             check (event_type in (
                                                                   'THREAT_DEFEATED',
                                                                   'SUPPLY_FOUND',
                                                                   'MISSION_COMPLETED',
                                                                   'TRADE_COMPLETED',
                                                                   'ALLY_RESCUED',
                                                                   'BASE_UPGRADED'
                                                 )),
                                         region varchar(40),
                                         event_key varchar(80) not null unique,
                                         description varchar(255),
                                         primary key (id)
);

-- ==========================================================
-- ÍNDICES
-- ==========================================================

create index idx_event_occurred_at
    on survivor_activity_event (occurred_at);

-- ==========================================================
-- FOREIGN KEYS
-- ==========================================================

alter table recursos
    add constraint fk_recurso_sobrevivente
        foreign key (sobrevivente_id)
            references sobreviventes;

alter table sobrevivente_comunidade
    add constraint FK6eo93n5rrilxijyt3emkdo1yl
        foreign key (comunidade_id)
            references comunidades;

alter table sobrevivente_comunidade
    add constraint FKf7bbc999axrn536x6b8bp0101
        foreign key (sobrevivente_id)
            references sobreviventes;

alter table sobreviventes_recursos
    add constraint FKanvyykdar9nto6oqobib5ty54
        foreign key (recursos_id)
            references recursos;

alter table sobreviventes_recursos
    add constraint FK2xvih9jpjtg2j0txa14dcsnah
        foreign key (sobrevivente_id)
            references sobreviventes;